#
# Executes commands at the start of an interactive session.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# iterm shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# source virtualenv
source /usr/local/bin/virtualenvwrapper_lazy.sh

# Exports environment variables defined in a .env or .localenv file
function setenv() {
  if [ -f .env ]; then
    export $(cat .env | xargs)
  fi
  if [ -f .localenv ]; then
    export $(cat .localenv | xargs)
  fi
}

function randomness(){
  export RANDOMNESS=$(openssl rand -base64 10)
}

#
# Docker
#

zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

function dcr() {
   echo "DCR'in $@"
   randomness
   docker-compose up --build $@
}

#
# Python
#

# generate ctags for entire python environment and project directory
function pytags() {
  ctags -R --fields=+l --languages=python -f ./tags $(python -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))") && \
  pytags-append
}

# append existing ctags file with current directories tags
function pytags-append() {
  ctags -R --fields=+l --languages=python -a -f ./tags .
}
